server:
  port: 8002

spring:
  redis:
    host: 34.88.24.200
    port: 6379
    password: ${redispass}

logging:
  file:
    path: logs/PriceService.log
  level:
    root: DEBUG

springdoc:
  api-docs:
    path: /api-docs
