server:
  port: 8002

spring:
  redis:
    host: localhost
    port: 8003
    database: 0

logging:
  file:
    path: logs/PriceService.log
  level:
    root: DEBUG

springdoc:
  api-docs:
    path: /api-docs
