server:
  port: 8002

api :
  tinkoffService : ${gcpTinkoffService}
  getPricesByFigies : /prices

spring:
  redis:
    host: ${redishost}
    port: ${redisport}
    password: ${redispass}

logging:
  level:
    root: INFO
  file:
    name: logs/PriceService.log


springdoc:
  api-docs:
    path: /api-docs
