server:
  port: 8002

api :
  tinkoffService : 'http://localhost:8003'
  getPricesByFigies : /prices

spring:
  redis:
    host: 34.88.96.185
    port: 6379
    password: ${redispass}

logging:
  file:
    path: logs/PriceService.log
  level:
    root: INFO

springdoc:
  api-docs:
    path: /api-docs
