server:
  port: 8003

api :
  stockConfig :
    stockService : ${gcpStockService}
    getPrices : /stocks/prices


spring:
  redis:
    host: ${redishost}
    port: ${redisport}
    password: ${redispass}

logging:
  level:
    root: INFO
  file:
    name: logs/PriceService.log


springdoc:
  api-docs:
    path: /api-docs
